### ISSUE TITLE
New cheat sheet proposal: Secrets Management

### ISSUE THREAD

**Issue by dominikdesmit** [OWASP/CheatSheetSeries#124]
Hi guys,

At the Open Security Summit 2019 we started working on a cheat sheet for Secrets Management: https://open-security-summit.org/tracks/devsecops/working-sessions/secrets-management/. The results are captured here: https://github.com/dominikdesmit/owasp-secrets-management. I think this would be very relevant also for this project and in terms of visibility. 

There is a big need for more guidance around secrets management and currently there are no guidelines from OWASP. With this cheat sheet we hope to fill that gap! 

Do you guys think it would be a good idea to put this cheat sheet under this project or should it be a separate one?

Thanks!

1. - [x] improve 2.2 Centralized Approach a bit (into standardized/fit-for-purpose) (see https://github.com/OWASP/CheatSheetSeries/pull/784/files) (@commjoen )
2. - [x]  cherrypick https://github.com/dominikdesmit/CheatSheetSeries/blob/master/cheatsheets/Secrets_Management_Cheat_Sheet.md what can be used immediately (@dominikdesmit)
3. - [x]  improve 2.5 Auditing (see https://github.com/OWASP/CheatSheetSeries/pull/784/files) (@commjoen - #791 )
4. - [x]  improve 2.9 Restore and Backup (see https://github.com/OWASP/CheatSheetSeries/pull/784/files) (@commjoen -#791)
5. - [x]  improve 2.10 Policies (see https://github.com/OWASP/CheatSheetSeries/pull/784/files) (@commjoen )
6. - [x] add 2.11 (metadata) (@commjoen )
7. - [x]  ~to discuss: maybe restructure 2 in order to focus on the basics firsts and split the advanced materials (and more vendor related) from it. (See https://xebia.com/blog/secure-deployment-10-pointers-on-secrets-management/ as well for osme of the topics).~ will be done post-mvp
8. - [x]  write basic outline of 3 (e.g. have filled in what we want to touch per paragraph, then replace this task with detailed tasks and fill in what you can already fill in, with resources linked already, see https://github.com/OWASP/CheatSheetSeries/pull/784/files for notes) (@commjoen ) - #816 
9. - [x]  write basic outline of 4(e.g. have filled in what we want to touch per paragraph, then replace this task with detailed tasks and fill in what you can already fill in, with resources linked already) (@bendehaan  & @commjoen ) - WIP @ #816 / #822 
10. - [x]  write basic outline of 5 (e.g. have filled in what we want to touch per paragraph, then replace this task with detailed tasks and fill in what you can already fill in, with resources linked already) (@commjoen ) - #816 
11. - [x]  write basic outline of 6(e.g. have filled in what we want to touch per paragraph, then replace this task with detailed tasks and fill in what you can already fill in, with resources linked already) (@commjoen , but can use help, see #822, #829)
12. - [x]  write basic outline of 7 (e.g. have filled in what we want to touch per paragraph, then replace this task with detailed tasks and fill in what you can already fill in, with resources linked already) (@commjoen) - #816  / #822 / #829
13. - [x]  ~write basic outline of 8 ~(~e.g. have filled in what we want to touch per paragraph, then replace this task with detailed tasks and fill in what you can already fill in, with resources linked already~) - skipping as part of mvp
14. - [x]  write basic outline of 9 (e.g. have filled in what we want to touch per paragraph, then replace this task with detailed tasks and fill in what you can already fill in, with resources linked already) (@thatsjet )
15. - [x]  ~write basic outline of 10~ (~e.g. have filled in what we want to touch per paragraph, then replace this task with detailed tasks and fill in what you can already fill in, with resources linked already~)   - removed, possibly come back post mvp
16. - [x]  write basic outline of 11 (secret detection) (e.g. have filled in what we want to touch per paragraph, then replace this task with detailed tasks and fill in what you can already fill in, with resources linked already)(@thatsjet )
17. - [x]  add further reading at https://gist.github.com/maxvt/bb49a6c7243163b8120625fc8ae3f3cd 
18. - [x] sync with ASVS (via opencre in #829)

**Comment by mackowski** [comment]
Yes, Yes, Yes :) 
I wanted to add secrets management to our roadmap so I am very supportive for this one 👍 
After we create it I can link to this CS from other CSs where it will be relevant.

**Comment by mackowski** [comment]
Here is also very good resource about tools: https://gist.github.com/maxvt/bb49a6c7243163b8120625fc8ae3f3cd

**Comment by dominikdesmit** [comment]
@mackowski awesome, yes you can!

**Comment by righettod** [comment]
All your defensive cheat sheet belong to us :) :) :) . We will be more than
happy to include and maintain it into the cheat sheet series house.

**Comment by mackowski** [comment]
Hey @dominikdesmit are you still working on this? Do you need any help from us?

**Comment by righettod** [comment]
Hello, 

As the issue is assigned since many time and we do not have received any PR for this then we send it back to the backlog and we set it as **HELP_WANTED**.

Thank you very much in advance for your understanding 😃

**Comment by jmanico** [comment]
BUMP this is a great idea.

**Comment by ykcab** [comment]
@mackowski [this is one](https://github.com/OWASP/CheatSheetSeries/issues/124#issuecomment-499823573) only lists tools, shouldn't this have to be more practical on how to use or implement them into [these services](https://github.com/dominikdesmit/owasp-secrets-management)

**Comment by mackowski** [comment]
Yes, this needs to be combined together. In general a lot of work is needed for this but if @ykcab or @dominikdesmit you want to create PR and work on this with us it will be awesome.

**Comment by dominikdesmit** [comment]
Hey @mackowski, sorry for not responding anymore! I was really busy with some other things. I would like to pick this up again but I would require some help :) 

I was also thinking about reaching out to other secrets management experts in the field, maybe people like Armon Dadgar would like to help out as well? 

The latest status is here actually: https://github.com/dominikdesmit/CheatSheetSeries/blob/master/cheatsheets/Secrets_Management_Cheat_Sheet.md

Let me know your thoughts @mackowski @ykcab!

**Comment by mackowski** [comment]
Sure we will help 👍 no worries. I suggest to make a PR here to make it easy to collaborate and share feedback. 

CC: @antfie @ armon

**Comment by ykcab** [comment]
Sure, @dominikdesmit. I'll be happy to contribute.

**Comment by hacksingh** [comment]
I would love to help and collaborate with you folks.

**Comment by mackowski** [comment]
Awesome @dominikdesmit if you can create PR and @ykcab and @hacksingh will be able to add more content and comment to it. 
Please when adding new content consider to review some other CheatSheets e.g. Cryptographic_Storage_Cheat_Sheet - and either link to it in relevant places OR suggest to remove some content from older CS and link from there to the new one. The point is to have (if possible) one place in whole project for one subject (e.g. key rotation)

**Comment by shploo** [comment]
I'm looking for knowledge

**Comment by jmanico** [comment]
I think this is a very important cheatsheet and I would like to help. Am I allowed to cherrypick from the resources mentioned above?

**Comment by thatsjet** [comment]
I'd be very interested in helping as well. Let me know if there is an area of focus I can put attention on.

**Comment by ykcab** [comment]
We were or are still waiting for a PR to come thru as per [this comment ](https://github.com/OWASP/CheatSheetSeries/issues/124#issuecomment-669740700).
Alternatively, we may begin our work by referring to the resources I pointed [here](https://github.com/OWASP/CheatSheetSeries/issues/124#issuecomment-668743684)

**Comment by jmanico** [comment]
That was 9 months ago or so. Is there something we can do to speed this along?

**Comment by commjoen** [comment]
@bendehaan, @dominikdesmit and I will try to push this again. For now we want to separate a few items and have actions defined/split here. Please note that this comment on the ticket is something that we will update quite often the upcoming days ;-)or move to a separate ticket if this gets frustrating. 
Actions for now on the SM cheatsheet:
- [ ] improve ### 2.2 Centralized Approach a bit (into standardized/fit-for-purpose) (see https://github.com/OWASP/CheatSheetSeries/pull/784/files)
- [ ] improve ### 2.5 Auditing (see https://github.com/OWASP/CheatSheetSeries/pull/784/files)
- [ ] improve ### 2.9 Restore and Backup (see https://github.com/OWASP/CheatSheetSeries/pull/784/files)
- [ ] improve ### 2.10 Policies (see https://github.com/OWASP/CheatSheetSeries/pull/784/files)
- [ ] restructure 2 in order to focus on the basics firsts and split the advanced materials (and more vendor related) from it. (See https://xebia.com/blog/secure-deployment-10-pointers-on-secrets-management/ as well).
- [ ] write basic outline of #3 (e.g. have filled in what we want to touch per paragraph, then replace this task with detailed tasks and fill in what you can already fill in, with resources linked already, see https://github.com/OWASP/CheatSheetSeries/pull/784/files for notes)
- [ ] write basic outline of #4(e.g. have filled in what we want to touch per paragraph, then replace this task with detailed tasks and fill in what you can already fill in, with resources linked already)
- [ ] write basic outline of #5 (e.g. have filled in what we want to touch per paragraph, then replace this task with detailed tasks and fill in what you can already fill in, with resources linked already)
- [ ] write basic outline of #6(e.g. have filled in what we want to touch per paragraph, then replace this task with detailed tasks and fill in what you can already fill in, with resources linked already)
- [ ] write basic outline of #7 (e.g. have filled in what we want to touch per paragraph, then replace this task with detailed tasks and fill in what you can already fill in, with resources linked already)
- [ ] write basic outline of #8 (e.g. have filled in what we want to touch per paragraph, then replace this task with detailed tasks and fill in what you can already fill in, with resources linked already)
- [ ] write basic outline of #9 (e.g. have filled in what we want to touch per paragraph, then replace this task with detailed tasks and fill in what you can already fill in, with resources linked already)
- [ ] write basic outline of #10 (e.g. have filled in what we want to touch per paragraph, then replace this task with detailed tasks and fill in what you can already fill in, with resources linked already)
- [ ] write basic outline of #11(e.g. have filled in what we want to touch per paragraph, then replace this task with detailed tasks and fill in what you can already fill in, with resources linked already)

**Comment by commjoen** [comment]
Note , we have a meeting on the subject at 08:30 CET tomorrow (thursday) to discuss outline and structure work a bit. Sorry for the late inclusion of you all (as we just had a chat yesterday about this subject and wanted to start moving a bit).
@ykcab i really like your suggestion made at https://github.com/OWASP/CheatSheetSeries/issues/124#issuecomment-830852181, only the problem is that if we make it so implementation focused, that we have to keep it up with every tool  and that is a bit too much for me. Would it be helpful if the cheatsheet is a bit more generic and then points, for each tool, to the right website? (or just include the resources mentioned by you as a read-more and part of the "select a fit-for-purpose tool" section in the cheatsheet?

**Comment by commjoen** [comment]
to speed up the interaction a bit: i have created a channel in slack: https://owasp.slack.com/archives/C02LSHXKVU5 . Together, with this issue we should be able to divide work and do stuff together :)

**Comment by commjoen** [comment]
I have moved the todos :)

**Comment by commjoen** [comment]
Meetingnotes:
- tasks are set in https://github.com/OWASP/CheatSheetSeries/issues/124, if you want to pick up a task, let us know here and we will assign it to you
- put the task-result in an PR towards the secretmanagement-cheatsheet branch so we can review it. Make as little PRs as possible (e.g. with the task executed, then PR directly) so you can get feedback fast and we can built the cheatsheet fast
- the focus of the chatsheet should be “what should you consider” and with the intention “prepare to migrate if requried because it is not that mature :smile: ”

**Comment by jmanico** [comment]
I appreciate the progress being made here!

**Comment by commjoen** [comment]
We have dropped the whole vendor lockin part as that is not very relevant for cloud providers,  #816  for WIP (please do NOT merge yet).

**Comment by commjoen** [comment]
Hi all, as you can tell, we are slowly making progress, but it is quite a lot that has to be written. CAn you for now please help reviewing section 3 of https://github.com/OWASP/CheatSheetSeries/pull/816 :) ? so that we can move ahead with the next sections. We are loking for feedbakc as well to understand whether the content written is actually helpful :).

**Comment by commjoen** [comment]
Anybody wants to help by picking up a task of the list above?

**Comment by commjoen** [comment]
Hi there, we are now checking if we really need section 8 for the MVP. And will try to close down sections 4 with @bendehaan and section 9 and 11 with @thatsjet . Let's see if we can redivide this work to speed up its writing! MVP time :)

**Comment by commjoen** [comment]
With https://github.com/OWASP/CheatSheetSeries/pull/840 the mVP is almost done! When it is merged, we can close this issue i guess.

**Comment by commjoen** [comment]
IT IS ALIVE!

**Comment by jmanico** [comment]
FANTASTIC WORK TEAM!

**Comment by commjoen** [comment]
Let's close this in favor of https://github.com/OWASP/CheatSheetSeries/issues/845, again: thank you for your work everybody!
